const games = [
  // Shooter Games
  { name: "Free Fire", category: "shooter", description: "Free Fire is a battle royale game where players fight to be the last one standing.", howToPlay: "Land on the map, collect weapons, and eliminate opponents while staying within the safe zone." },
  { name: "PUBG", category: "shooter", description: "PUBG is a realistic battle royale game.", howToPlay: "Loot weapons and gear, survive, and aim for the Chicken Dinner." },
  { name: "Call of Duty: Mobile", category: "shooter", description: "COD Mobile brings iconic Call of Duty gameplay to mobile.", howToPlay: "Play in various modes, from Battle Royale to Team Deathmatch." },
  { name: "Valorant", category: "shooter", description: "Valorant is a team-based tactical shooter game.", howToPlay: "Choose an agent, strategize with your team, and defeat enemies in rounds." },
  { name: "Overwatch", category: "shooter", description: "Overwatch is a team-based multiplayer FPS with diverse heroes.", howToPlay: "Use your hero's unique abilities to secure objectives and defeat enemies." },
  { name: "Counter-Strike: Global Offensive", category: "shooter", description: "CS:GO is a competitive multiplayer FPS.", howToPlay: "Work as a team to secure objectives and eliminate the opposing team." },
  { name: "Rainbow Six Siege", category: "shooter", description: "A tactical shooter game focused on strategy and teamwork.", howToPlay: "Choose your operator, secure objectives, and outsmart your opponents." },
  { name: "Battlefield 2042", category: "shooter", description: "A large-scale multiplayer FPS game.", howToPlay: "Work as a team, capture objectives, and defeat the enemy forces." },
  { name: "Fortnite", category: "shooter", description: "A colorful battle royale game with building mechanics.", howToPlay: "Fight enemies, build structures, and be the last person standing." },
  { name: "Halo Infinite", category: "shooter", description: "A futuristic FPS game with advanced weaponry.", howToPlay: "Fight enemies in campaign mode or dominate in multiplayer battles." },

  // Racing Games
  { name: "Indian Bike Driving 3D", category: "racing", description: "A sandbox driving game popular in India and Pakistan.", howToPlay: "Drive bikes, cars, and explore the open world with various challenges." },
  { name: "Need for Speed: Most Wanted", category: "racing", description: "A high-speed street racing game with cop chases.", howToPlay: "Race against opponents and evade the police to become the most wanted." },
  { name: "Asphalt 9: Legends", category: "racing", description: "Asphalt 9 is an arcade racing game with luxury cars.", howToPlay: "Race through tracks, perform stunts, and unlock new vehicles." },
  { name: "Forza Horizon 5", category: "racing", description: "An open-world racing game set in Mexico.", howToPlay: "Participate in events, explore the map, and drive exotic cars." },
  { name: "Euro Truck Simulator 2", category: "racing", description: "A realistic truck driving simulation game.", howToPlay: "Drive trucks across Europe, deliver goods, and expand your business." },
  { name: "Mario Kart 8 Deluxe", category: "racing", description: "A fun arcade racing game featuring Nintendo characters.", howToPlay: "Race against friends, use power-ups, and win trophies." },
  { name: "F1 2023", category: "racing", description: "A realistic Formula 1 racing simulation.", howToPlay: "Race on official F1 tracks with licensed teams and cars." },
  { name: "Hill Climb Racing", category: "racing", description: "A fun physics-based driving game.", howToPlay: "Drive uphill while managing fuel and avoiding obstacles." },
  { name: "Truck Simulator: Ultimate", category: "racing", description: "A detailed truck driving simulation game.", howToPlay: "Complete deliveries, manage your fleet, and expand your business." },
  { name: "City Racing 3D", category: "racing", description: "A simple yet fun racing game.", howToPlay: "Race through cities, upgrade cars, and win championships." },

  // Adventure Games
  { name: "The Legend of Zelda: Breath of the Wild", category: "adventure", description: "A vast open-world adventure game.", howToPlay: "Solve puzzles, defeat enemies, and uncover secrets across Hyrule." },
  { name: "GTA V", category: "adventure", description: "An open-world action-adventure game.", howToPlay: "Complete missions, explore the world, and interact with NPCs in various ways." },
  { name: "Assassin's Creed Valhalla", category: "adventure", description: "An action-adventure game set in the Viking era.", howToPlay: "Lead your clan, fight enemies, and uncover a gripping story." },
  { name: "Horizon Zero Dawn", category: "adventure", description: "An open-world game featuring a post-apocalyptic Earth.", howToPlay: "Explore the world, hunt robotic creatures, and unravel mysteries." },
  { name: "Red Dead Redemption 2", category: "adventure", description: "A western-themed open-world adventure.", howToPlay: "Complete missions, explore the wild west, and survive against outlaws." },
  { name: "Minecraft", category: "adventure", description: "A sandbox game where you can build and explore.", howToPlay: "Gather resources, build structures, and survive against enemies." },
  { name: "Subnautica", category: "adventure", description: "An underwater survival and exploration game.", howToPlay: "Explore the ocean, craft tools, and uncover the planet's secrets." },
  { name: "The Witcher 3: Wild Hunt", category: "adventure", description: "An open-world RPG featuring Geralt of Rivia.", howToPlay: "Complete quests, defeat monsters, and shape your story with choices." },
  { name: "Terraria", category: "adventure", description: "A 2D sandbox exploration game.", howToPlay: "Mine resources, craft items, and defeat bosses to progress." },
  { name: "Journey", category: "adventure", description: "A meditative adventure game set in a desert.", howToPlay: "Explore ruins, solve puzzles, and reach the mountain's summit." },

  // (Continue adding games up to 250 for this part)
];
games.push(
  // Puzzle Games
  { name: "Candy Crush Saga", category: "puzzle", description: "A popular match-3 puzzle game.", howToPlay: "Match candies of the same color to complete objectives within moves." },
  { name: "2048", category: "puzzle", description: "A simple yet addictive number-merge game.", howToPlay: "Swipe tiles to combine them and reach 2048." },
  { name: "Tetris", category: "puzzle", description: "A classic block-stacking game.", howToPlay: "Arrange falling blocks to clear rows and score points." },
  { name: "Portal 2", category: "puzzle", description: "A physics-based puzzle game.", howToPlay: "Use a portal gun to solve puzzles and progress through the story." },
  { name: "The Room", category: "puzzle", description: "A tactile puzzle game with mystery elements.", howToPlay: "Interact with objects and uncover secrets to solve the puzzles." },
  { name: "Lumosity", category: "puzzle", description: "A collection of brain-training games.", howToPlay: "Play games designed to improve memory, attention, and problem-solving skills." },
  { name: "Unblock Me", category: "puzzle", description: "A sliding puzzle game.", howToPlay: "Move blocks to create a path and free the red block." },
  { name: "Monument Valley", category: "puzzle", description: "A surreal exploration and puzzle game.", howToPlay: "Guide the character through impossible architecture and optical illusions." },
  { name: "Sudoku", category: "puzzle", description: "A logic-based number placement game.", howToPlay: "Fill the grid so each column, row, and block contains 1-9." },
  { name: "Cut the Rope", category: "puzzle", description: "A physics-based puzzle game.", howToPlay: "Cut ropes in the correct order to feed candy to Om Nom." },

  // Sports Games
  { name: "FIFA 23", category: "sports", description: "A soccer simulation game.", howToPlay: "Control a team, score goals, and win matches in tournaments." },
  { name: "NBA 2K23", category: "sports", description: "A basketball simulation game.", howToPlay: "Play as real teams or create your own player to compete in matches." },
  { name: "Madden NFL 23", category: "sports", description: "An American football simulation game.", howToPlay: "Build a team and compete in football matches with strategic plays." },
  { name: "WWE 2K23", category: "sports", description: "A wrestling simulation game.", howToPlay: "Play as WWE superstars and compete in wrestling matches." },
  { name: "Rocket League", category: "sports", description: "A game that combines soccer with cars.", howToPlay: "Use rocket-powered vehicles to score goals in fast-paced matches." },
  { name: "Golf Clash", category: "sports", description: "A fun and competitive golf game.", howToPlay: "Compete against players online in quick golf matches." },
  { name: "Tony Hawk's Pro Skater 1+2", category: "sports", description: "A skateboarding simulation game.", howToPlay: "Perform tricks, complete challenges, and score points." },
  { name: "Cricket 19", category: "sports", description: "A realistic cricket simulation game.", howToPlay: "Play matches, manage teams, and compete in tournaments." },
  { name: "eFootball 2023", category: "sports", description: "A free-to-play soccer game.", howToPlay: "Compete in online matches and build your ultimate team." },
  { name: "Baseball 9", category: "sports", description: "A mobile baseball simulation game.", howToPlay: "Pitch, hit, and manage your team to win games." },

  // Casual Games
  { name: "Subway Surfers", category: "casual", description: "An endless runner game.", howToPlay: "Dodge trains and obstacles while collecting coins and power-ups." },
  );
  games.push(
  // Simulation Games
  { name: "The Sims 4", category: "simulation", description: "A life simulation game.", howToPlay: "Create characters, build houses, and manage their daily lives." },
  { name: "Animal Crossing: New Horizons", category: "simulation", description: "A relaxing island life simulator.", howToPlay: "Build and decorate your island, interact with villagers, and collect items." },
  { name: "Farming Simulator 22", category: "simulation", description: "A farming management simulation game.", howToPlay: "Plant crops, raise animals, and grow your farm." },
  { name: "Cities: Skylines", category: "simulation", description: "A city-building simulation game.", howToPlay: "Design and manage your own city, ensuring growth and happiness." },
  { name: "Planet Zoo", category: "simulation", description: "A zoo management simulation game.", howToPlay: "Build and manage a zoo while caring for animals and visitors." },
  { name: "Microsoft Flight Simulator", category: "simulation", description: "A realistic flight simulation game.", howToPlay: "Fly planes across the world in realistic weather conditions." },
  { name: "SimCity", category: "simulation", description: "A classic city-building simulation game.", howToPlay: "Build cities, manage resources, and grow your population." },
  { name: "RollerCoaster Tycoon", category: "simulation", description: "A theme park management game.", howToPlay: "Design roller coasters and manage park finances to keep visitors happy." },
  { name: "House Flipper", category: "simulation", description: "A home renovation simulation game.", howToPlay: "Buy, renovate, and sell houses for a profit." },
  { name: "Cooking Simulator", category: "simulation", description: "A realistic cooking game.", howToPlay: "Prepare dishes using real-life recipes and tools in a virtual kitchen." },

  // Horror Games
  { name: "Resident Evil Village", category: "horror", description: "A survival horror game.", howToPlay: "Explore a creepy village and fight terrifying creatures." },
  { name: "Outlast", category: "horror", description: "A first-person survival horror game.", howToPlay: "Explore a haunted asylum while avoiding dangerous enemies." },
  { name: "Phasmophobia", category: "horror", description: "A ghost-hunting cooperative horror game.", howToPlay: "Investigate haunted locations and collect evidence of paranormal activity." },
  { name: "Silent Hill 2", category: "horror", description: "A psychological horror game.", howToPlay: "Navigate a foggy town while solving puzzles and fighting monsters." },
  { name: "Five Nights at Freddy's", category: "horror", description: "A survival horror game set in a haunted pizzeria.", howToPlay: "Monitor security cameras and survive against animatronic creatures." },
  { name: "Dead by Daylight", category: "horror", description: "A multiplayer survival horror game.", howToPlay: "Survive as a team or hunt players as a killer." },
  { name: "The Evil Within", category: "horror", description: "A survival horror game.", howToPlay: "Escape from horrifying creatures and uncover dark secrets." },
  { name: "Amnesia: The Dark Descent", category: "horror", description: "A first-person survival horror game.", howToPlay: "Navigate a dark castle while avoiding enemies and solving puzzles." },
  { name: "Layers of Fear", category: "horror", description: "A psychological horror game.", howToPlay: "Explore a haunted house and uncover the story of a tormented painter." },
  { name: "Little Nightmares", category: "horror", description: "A puzzle-platformer horror game.", howToPlay: "Guide a small character through a creepy and dangerous world." },

  // MMORPG Games
  { name: "World of Warcraft", category: "mmorpg", description: "A fantasy MMORPG.", howToPlay: "Complete quests, join raids, and explore a vast world with other players." },
  { name: "Final Fantasy XIV", category: "mmorpg", description: "A popular MMORPG in the Final Fantasy series.", howToPlay: "Explore the world of Eorzea, complete quests, and battle powerful enemies." },
  { name: "The Elder Scrolls Online", category: "mmorpg", description: "An MMORPG set in the Elder Scrolls universe.", howToPlay: "Explore Tamriel, complete quests, and join guilds in a massive online world." },
  { name: "Guild Wars 2", category: "mmorpg", description: "A dynamic MMORPG with a rich story.", howToPlay: "Choose your class, complete events, and explore a vast world." },
  { name: "Black Desert Online", category: "mmorpg", description: "A visually stunning MMORPG.", howToPlay: "Fight enemies, gather resources, and build your character in an open world." },
  { name: "Runescape", category: "mmorpg", description: "A classic MMORPG with an open-world design.", howToPlay: "Complete quests, train skills, and interact with players in a medieval world." },
  { name: "Lost Ark", category: "mmorpg", description: "An action MMORPG with stunning visuals.", howToPlay: "Explore dungeons, fight enemies, and complete quests with a party." },
  { name: "Blade & Soul", category: "mmorpg", description: "An MMORPG with martial arts combat.", howToPlay: "Choose a class, fight enemies, and explore a fantasy world." },
  { name: "Tibia", category: "mmorpg", description: "A classic 2D MMORPG.", howToPlay: "Explore dungeons, complete quests, and level up your character." },
  { name: "Star Wars: The Old Republic", category: "mmorpg", description: "An MMORPG set in the Star Wars universe.", howToPlay: "Join the Jedi or Sith, complete missions, and explore a galaxy far, far away." },

  // (Continue adding until 750 games)
);
games.push(
  // Strategy Games
  { name: "Clash of Clans", category: "strategy", description: "A mobile strategy game where you build and defend your village.", howToPlay: "Train troops, upgrade your base, and attack other players." },
  { name: "Age of Empires IV", category: "strategy", description: "A real-time strategy game set in historical eras.", howToPlay: "Build an empire, gather resources, and defeat opponents in battles." },
  { name: "Starcraft II", category: "strategy", description: "A sci-fi real-time strategy game.", howToPlay: "Control armies, gather resources, and outsmart your opponents." },
  { name: "Civilization VI", category: "strategy", description: "A turn-based strategy game.", howToPlay: "Lead a civilization through time and achieve victory through various means." },
  { name: "Total War: Warhammer III", category: "strategy", description: "A fantasy real-time strategy game.", howToPlay: "Command armies in epic battles and manage your kingdom." },
  { name: "XCOM 2", category: "strategy", description: "A turn-based strategy game with a focus on tactical combat.", howToPlay: "Lead a resistance force against alien invaders and manage resources." },
  { name: "Dota 2", category: "strategy", description: "A popular MOBA game.", howToPlay: "Work with your team to destroy the enemy's base." },
  { name: "League of Legends", category: "strategy", description: "A competitive multiplayer online battle arena game.", howToPlay: "Choose a champion, strategize with your team, and destroy the enemy nexus." },
  { name: "Warcraft III: Reforged", category: "strategy", description: "A remastered version of the classic RTS game.", howToPlay: "Control heroes and armies, build bases, and defeat opponents." },
  { name: "Anno 1800", category: "strategy", description: "A city-building strategy game.", howToPlay: "Develop a thriving city, manage resources, and trade with other settlements." },

  // Fighting Games
  { name: "Mortal Kombat 11", category: "fighting", description: "A brutal fighting game.", howToPlay: "Choose a character, fight opponents, and perform powerful combos." },
  { name: "Street Fighter V", category: "fighting", description: "A competitive fighting game.", howToPlay: "Master moves and combos to defeat opponents in battles." },
  { name: "Tekken 7", category: "fighting", description: "A popular 3D fighting game.", howToPlay: "Choose a character and fight in story mode or against other players." },
  { name: "Super Smash Bros. Ultimate", category: "fighting", description: "A crossover fighting game featuring Nintendo characters.", howToPlay: "Knock your opponents off the stage to win." },
  { name: "Injustice 2", category: "fighting", description: "A superhero-themed fighting game.", howToPlay: "Battle as DC characters and uncover the story in campaign mode." },
  { name: "Dragon Ball FighterZ", category: "fighting", description: "A fast-paced fighting game based on Dragon Ball.", howToPlay: "Form a team and fight using powerful moves and combos." },
  { name: "Soulcalibur VI", category: "fighting", description: "A weapon-based fighting game.", howToPlay: "Choose a character and master their unique fighting style." },
  { name: "Guilty Gear Strive", category: "fighting", description: "A stylish anime-style fighting game.", howToPlay: "Fight opponents using complex combos and special moves." },
  { name: "King of Fighters XV", category: "fighting", description: "A classic fighting game series.", howToPlay: "Form a team of fighters and compete in tournaments." },
  { name: "Dead or Alive 6", category: "fighting", description: "A 3D fighting game.", howToPlay: "Choose a character and fight in dynamic, interactive arenas." },

  // Indie Games
  { name: "Celeste", category: "indie", description: "A challenging platformer game.", howToPlay: "Climb a mountain while overcoming tough obstacles." },
  { name: "Hollow Knight", category: "indie", description: "A Metroidvania-style action-adventure game.", howToPlay: "Explore a mysterious underground world, fight enemies, and uncover secrets." },
  { name: "Stardew Valley", category: "indie", description: "A farming simulation game.", howToPlay: "Grow crops, raise animals, and build relationships with villagers." },
  { name: "Undertale", category: "indie", description: "A unique RPG game where you can choose to fight or spare enemies.", howToPlay: "Navigate a quirky world and make moral choices that affect the story." },
  { name: "Among Us", category: "indie", description: "A multiplayer social deduction game.", howToPlay: "Work as a crewmate or impostor to complete tasks or sabotage the mission." },
  { name: "Cuphead", category: "indie", description: "A run-and-gun game with 1930s-style animation.", howToPlay: "Fight bosses and overcome levels with challenging gameplay." },
  { name: "Inside", category: "indie", description: "A dark puzzle-platformer game.", howToPlay: "Solve puzzles and uncover the story of a dystopian world." },
  { name: "Terraria", category: "indie", description: "A sandbox exploration game.", howToPlay: "Mine resources, craft items, and defeat bosses to progress." },
  { name: "Oxenfree", category: "indie", description: "A supernatural thriller adventure game.", howToPlay: "Uncover mysteries and shape the story through dialogue choices." },
  { name: "Slime Rancher", category: "indie", description: "A fun farming game with adorable slimes.", howToPlay: "Capture slimes, manage resources, and build your ranch." },

  // (Continue adding games to reach 1000)
);
games.push(
  // Racing Games
  { name: "Need for Speed: Heat", category: "racing", description: "An open-world racing game.", howToPlay: "Compete in street races and outrun the cops in a dynamic world." },
  { name: "Mario Kart 8 Deluxe", category: "racing", description: "A kart racing game featuring Mario and friends.", howToPlay: "Race through fun tracks and use items to get ahead of opponents." },
  { name: "Forza Horizon 5", category: "racing", description: "An open-world racing game set in Mexico.", howToPlay: "Explore the world, participate in events, and race in diverse environments." },
  { name: "F1 2021", category: "racing", description: "A realistic Formula 1 racing game.", howToPlay: "Race against the best drivers in F1, manage your career, and win championships." },
  { name: "Wreckfest", category: "racing", description: "A car combat racing game.", howToPlay: "Destroy opponents in brutal races and derby events." },
  
  // Shooter Games
  { name: "Call of Duty: Warzone", category: "shooter", description: "A battle royale mode of the Call of Duty franchise.", howToPlay: "Fight for survival against up to 150 players in an ever-shrinking battlefield." },
  { name: "Fortnite", category: "shooter", description: "A popular battle royale game.", howToPlay: "Survive against 100 other players by gathering resources, building structures, and eliminating opponents." },
  { name: "Apex Legends", category: "shooter", description: "A free-to-play battle royale game.", howToPlay: "Choose a character with unique abilities and team up to be the last squad standing." },
  { name: "Overwatch 2", category: "shooter", description: "A team-based multiplayer first-person shooter.", howToPlay: "Pick a hero, work with your team, and complete objectives." },
  { name: "Rainbow Six Siege", category: "shooter", description: "A tactical first-person shooter focused on team strategy.", howToPlay: "Use unique operators and plan your attacks to breach fortified areas." },
  
  // RPG Games
  { name: "The Witcher 3: Wild Hunt", category: "rpg", description: "A deep RPG set in a medieval fantasy world.", howToPlay: "Explore a vast world, complete quests, and make choices that affect the story." },
  { name: "Skyrim", category: "rpg", description: "An open-world RPG set in a fantasy world.", howToPlay: "Explore dungeons, complete quests, and level up your character in a vast world." },
  { name: "Dark Souls III", category: "rpg", description: "A challenging action RPG.", howToPlay: "Fight through difficult enemies, explore intricate environments, and level up your character." },
  { name: "Persona 5", category: "rpg", description: "A Japanese role-playing game with social simulation elements.", howToPlay: "Build relationships, battle demons, and uncover mysteries in a Tokyo high school." },
  { name: "Cyberpunk 2077", category: "rpg", description: "An open-world RPG set in a dystopian future.", howToPlay: "Take on missions, upgrade your character, and explore the futuristic city of Night City." },
  
  // Strategy Games
  { name: "Sid Meier's Civilization VI", category: "strategy", description: "A turn-based strategy game where you build a civilization.", howToPlay: "Expand your empire, develop technologies, and conquer your enemies to dominate the world." },
  { name: "Company of Heroes 2", category: "strategy", description: "A real-time strategy game set during World War II.", howToPlay: "Control infantry and tanks in strategic combat scenarios." },
  { name: "Command & Conquer: Red Alert 3", category: "strategy", description: "A real-time strategy game with a focus on combat.", howToPlay: "Command one of several factions in global warfare, using strategic resources and armies." },
  { name: "Hearts of Iron IV", category: "strategy", description: "A grand strategy game set in World War II.", howToPlay: "Control a nation, make strategic decisions, and lead it through the war." },
  { name: "Age of Mythology", category: "strategy", description: "A real-time strategy game set in a mythological world.", howToPlay: "Build cities, gather resources, and summon mythical creatures to fight for you." },
  
  // Indie Games
  { name: "Hades", category: "indie", description: "A rogue-like dungeon crawler where you play as the son of Hades.", howToPlay: "Fight your way out of the underworld and upgrade your abilities with each run." },
  { name: "Hotline Miami", category: "indie", description: "A top-down action game with a neon-lit aesthetic.", howToPlay: "Use quick reflexes and strategy to take down enemies in fast-paced combat." },
  { name: "Bastion", category: "indie", description: "A visually stunning action RPG.", howToPlay: "Explore a world destroyed by disaster, battling enemies and rebuilding the world." },
  { name: "Dead Cells", category: "indie", description: "A rogue-like action-platformer.", howToPlay: "Explore a constantly changing world, battle enemies, and unlock new abilities." },
  { name: "Super Meat Boy", category: "indie", description: "A fast-paced platformer game.", howToPlay: "Jump, run, and avoid obstacles in difficult levels to rescue your girlfriend." },

  // Fighting Games
  { name: "Dragon Ball Z: Kakarot", category: "fighting", description: "An action RPG based on the Dragon Ball Z series.", howToPlay: "Control Goku and other iconic characters in battles against powerful foes." },
  { name: "Soulcalibur VI", category: "fighting", description: "A weapon-based fighting game.", howToPlay: "Fight using various characters with different fighting styles and weapons." },
  { name: "Mortal Kombat XL", category: "fighting", description: "A brutal, over-the-top fighting game.", howToPlay: "Defeat opponents in violent battles with a mix of brutal combat moves and fatalities." },
  { name: "Tekken 7", category: "fighting", description: "A 3D fighting game with strategic gameplay.", howToPlay: "Choose a character and compete against others in one-on-one battles." },
  { name: "Injustice: Gods Among Us", category: "fighting", description: "A fighting game set in the DC Universe.", howToPlay: "Use iconic heroes and villains in epic battles with unique superpowers." },
  
  // Simulation Games
  { name: "SimCity 4", category: "simulation", description: "A city-building simulation game.", howToPlay: "Create and manage a city while balancing resources and infrastructure." },
  { name: "RollerCoaster Tycoon 2", category: "simulation", description: "A theme park simulation game.", howToPlay: "Design and manage a theme park, building rides, and keeping guests happy." },
  { name: "Planet Coaster", category: "simulation", description: "A theme park simulation game focusing on roller coaster design.", howToPlay: "Design and manage roller coasters and theme parks to entertain guests." },
  { name: "Cities in Motion", category: "simulation", description: "A public transportation management simulation game.", howToPlay: "Design and manage transportation systems in a city." },
  { name: "Prison Architect", category: "simulation", description: "A prison management simulation game.", howToPlay: "Design and manage a prison, including building cells, managing staff, and handling inmates." },
  
  // Sports Games
  { name: "PES 2021", category: "sports", description: "A soccer simulation game.", howToPlay: "Compete with other teams in leagues and tournaments to win championships." },
  { name: "Pro Evolution Soccer 2018", category: "sports", description: "A soccer game focused on realism.", howToPlay: "Play as your favorite soccer teams and win tournaments." },
  { name: "NBA 2K20", category: "sports", description: "A basketball simulation game.", howToPlay: "Play through the NBA season or build your own team to compete against others." },
  { name: "FIFA 19", category: "sports", description: "A soccer simulation game.", howToPlay: "Play in tournaments or career mode as you manage your soccer team." },
  { name: "WWE 2K20", category: "sports", description: "A wrestling simulation game.", howToPlay: "Create and control wrestlers in epic WWE matches." }
);
games.push(
  // Adventure Games
  { name: "Red Dead Redemption 2", category: "adventure", description: "An open-world action-adventure game set in the Wild West.", howToPlay: "Explore a massive world, complete missions, and interact with characters." },
  { name: "The Legend of Zelda: Breath of the Wild", category: "adventure", description: "A critically acclaimed open-world adventure game.", howToPlay: "Explore the vast world of Hyrule, solve puzzles, and defeat enemies." },
  { name: "Uncharted 4: A Thief's End", category: "adventure", description: "An action-adventure game with exploration and puzzle-solving.", howToPlay: "Solve puzzles, climb mountains, and defeat enemies in a treasure hunt adventure." },
  { name: "Tomb Raider (2013)", category: "adventure", description: "A reboot of the classic adventure series, focusing on Lara Croft's origin.", howToPlay: "Solve puzzles, explore ancient tombs, and fight enemies in a survival setting." },
  { name: "The Last of Us Part II", category: "adventure", description: "An action-adventure game set in a post-apocalyptic world.", howToPlay: "Explore, craft, and engage in combat while uncovering an emotional story." },

  // Puzzle Games
  { name: "The Witness", category: "puzzle", description: "A first-person puzzle game set on a mysterious island.", howToPlay: "Solve puzzles based on visual clues and patterns to unlock the island's secrets." },
  { name: "Portal 2", category: "puzzle", description: "A physics-based puzzle game where you manipulate portals.", howToPlay: "Use portals to navigate through levels and solve increasingly complex puzzles." },
  { name: "Lara Croft and the Temple of Osiris", category: "puzzle", description: "An action-puzzle game based on Egyptian mythology.", howToPlay: "Solve puzzles, explore ancient temples, and fight enemies with Lara Croft." },
  { name: "Braid", category: "puzzle", description: "A platformer with time manipulation mechanics.", howToPlay: "Solve puzzles by controlling time to reach new areas and progress." },
  { name: "The Talos Principle", category: "puzzle", description: "A first-person puzzle game with philosophical elements.", howToPlay: "Solve puzzles and uncover the mystery behind your existence." },

  // Simulation Games
  { name: "Microsoft Flight Simulator 2020", category: "simulation", description: "A highly realistic flight simulation game.", howToPlay: "Pilot various aircrafts around the world using realistic weather and physics." },
  { name: "Euro Truck Simulator 2", category: "simulation", description: "A truck driving simulation game in Europe.", howToPlay: "Drive a truck across Europe, deliver goods, and manage your trucking business." },
  { name: "Farming Simulator 19", category: "simulation", description: "A farming simulation game where you grow crops and raise animals.", howToPlay: "Plant, harvest, and manage a farm to make profits while expanding your business." },
  { name: "Cooking Simulator", category: "simulation", description: "A cooking simulation game with realistic kitchen mechanics.", howToPlay: "Prepare meals, use kitchen tools, and manage a virtual restaurant." },
  { name: "Planet Coaster", category: "simulation", description: "A theme park simulation game where you design and manage your own park.", howToPlay: "Create roller coasters, manage rides, and keep your guests entertained." },

  // MMORPG Games
  { name: "World of Warcraft", category: "mmorpg", description: "A massively multiplayer online role-playing game set in the fantasy world of Azeroth.", howToPlay: "Complete quests, level up your character, and fight against players and monsters." },
  { name: "Final Fantasy XIV", category: "mmorpg", description: "A popular MMORPG set in the world of Eorzea.", howToPlay: "Complete quests, join guilds, and battle monsters with other players." },
  { name: "Guild Wars 2", category: "mmorpg", description: "A free-to-play MMORPG set in the fantasy world of Tyria.", howToPlay: "Explore the world, fight enemies, and join dynamic events in a living world." },
  { name: "Elder Scrolls Online", category: "mmorpg", description: "An MMORPG set in the Elder Scrolls universe.", howToPlay: "Complete quests, explore Tamriel, and team up with others to battle monsters and bosses." },
  { name: "Star Wars: The Old Republic", category: "mmorpg", description: "An MMORPG set in the Star Wars universe.", howToPlay: "Create a character, join factions, and experience the story as you explore the galaxy." },

  // Horror Games
  { name: "Resident Evil 2 (Remake)", category: "horror", description: "A survival horror game set in the aftermath of a zombie outbreak.", howToPlay: "Survive against zombies, solve puzzles, and fight terrifying creatures." },
  { name: "Amnesia: The Dark Descent", category: "horror", description: "A first-person survival horror game.", howToPlay: "Explore a dark mansion, solve puzzles, and survive terrifying encounters with supernatural entities." },
  { name: "Outlast", category: "horror", description: "A first-person survival horror game set in an insane asylum.", howToPlay: "Navigate dark environments, avoid enemies, and uncover the truth behind the asylum." },
  { name: "Layers of Fear", category: "horror", description: "A psychological horror game set in a Victorian mansion.", howToPlay: "Solve puzzles and uncover the dark past of an artist while dealing with disturbing hallucinations." },
  { name: "Silent Hill 2", category: "horror", description: "A classic survival horror game in the Silent Hill series.", howToPlay: "Explore the mysterious town of Silent Hill, solve puzzles, and survive against horrific creatures." },

  // Fighting Games
  { name: "Guilty Gear Strive", category: "fighting", description: "A stylish 2D fighter with anime-inspired visuals.", howToPlay: "Master characters with unique moves and combos to defeat your opponents." },
  { name: "Street Fighter IV", category: "fighting", description: "A classic 2D fighting game with a huge roster of fighters.", howToPlay: "Battle opponents using a mix of special moves and combos." },
  { name: "Tekken 6", category: "fighting", description: "A fast-paced 3D fighting game with complex mechanics.", howToPlay: "Choose a fighter and use a variety of punches, kicks, and combos to defeat your opponent." },
  { name: "Virtua Fighter 5", category: "fighting", description: "A 3D fighting game with deep combat mechanics.", howToPlay: "Fight in various arenas using characters with unique fighting styles." },
  { name: "Dead or Alive 5", category: "fighting", description: "A fighting game featuring both traditional combat and interactive environments.", howToPlay: "Choose a fighter and engage in fast-paced combat with devastating moves." },

  // Casual Games
  { name: "Animal Crossing: New Horizons", category: "casual", description: "A life-simulation game where you build and decorate your island.", howToPlay: "Catch bugs, fish, and interact with island villagers to create your dream island." },
  { name: "Minecraft", category: "casual", description: "A sandbox game where you can build and explore virtual worlds.", howToPlay: "Gather resources, build structures, and explore a blocky world in creative or survival mode." },
  { name: "The Sims 4", category: "casual", description: "A life simulation game where you create and control virtual people.", howToPlay: "Build houses, form relationships, and guide Sims through their daily lives." },
  { name: "Farmville 2", category: "casual", description: "A farming simulation game with casual gameplay.", howToPlay: "Plant crops, raise animals, and decorate your farm to keep it running." },
  { name: "Candy Crush Saga", category: "casual", description: "A match-3 puzzle game with hundreds of levels.", howToPlay: "Match colorful candies to clear levels and complete objectives." },

  // Sandbox Games
  { name: "No Man's Sky", category: "sandbox", description: "A space exploration sandbox game.", howToPlay: "Explore planets, mine resources, and build bases in an infinite universe." },
  { name: "Terraria", category: "sandbox", description: "A 2D sandbox adventure game with crafting elements.", howToPlay: "Dig, build, and battle creatures in a procedurally generated world." },
  { name: "Garry's Mod", category: "sandbox", description: "A physics-based sandbox game using the Source engine.", howToPlay: "Create and manipulate objects, play mini-games, or roleplay with others in a sandbox environment." },
  { name: "Rust", category: "sandbox", description: "A multiplayer survival game.", howToPlay: "Gather resources, build shelters, and survive against other players and environmental dangers." },
  { name: "ARK: Survival Evolved", category: "sandbox", description: "A survival game where players hunt and tame dinosaurs.", howToPlay: "Survive, build shelters, and tame creatures in an open world full of dinosaurs." }
);

games.push(
  { name: "Grand Theft Auto V", category: "action", description: "An open-world action game with heists and adventures.", howToPlay: "Complete missions or explore Los Santos freely." },
  { name: "Assassin's Creed Valhalla", category: "action", description: "An action RPG based on Norse mythology.", howToPlay: "Lead raids, explore England, and build your settlement." },
  { name: "Far Cry 6", category: "action", description: "An open-world first-person shooter with guerrilla warfare.", howToPlay: "Fight a dictator's forces while liberating your island." },
  { name: "Shadow of the Tomb Raider", category: "action", description: "A thrilling action-adventure game.", howToPlay: "Solve ancient puzzles and fight enemies to uncover secrets." },
  { name: "Control", category: "action", description: "A supernatural action game with reality-bending mechanics.", howToPlay: "Use powers and explore a mysterious building." },
  { name: "Cyberpunk 2077", category: "action", description: "An open-world action game set in a dystopian future.", howToPlay: "Complete missions and explore Night City with augmentations." },
  { name: "Hitman 3", category: "action", description: "A stealth-action game.", howToPlay: "Complete assassination missions in detailed, open-ended levels." },
  { name: "Watch Dogs 2", category: "action", description: "An open-world hacking adventure game.", howToPlay: "Hack systems, complete missions, and explore San Francisco." },
  { name: "Just Cause 4", category: "action", description: "A high-octane open-world action game.", howToPlay: "Cause chaos with grappling hooks and massive explosions." },
  { name: "Mad Max", category: "action", description: "A post-apocalyptic action game.", howToPlay: "Explore the wasteland, fight enemies, and upgrade your car." },
  { name: "Sleeping Dogs", category: "action", description: "An action game set in the criminal underworld of Hong Kong.", howToPlay: "Complete missions as an undercover cop in a vibrant city." },
  { name: "Middle-earth: Shadow of Mordor", category: "action", description: "An action game set in Tolkien's universe.", howToPlay: "Defeat orcs and conquer regions using the Nemesis system." },
  { name: "Batman: Arkham Knight", category: "action", description: "A superhero action game.", howToPlay: "Fight Gotham's villains and uncover the Arkham Knight's identity." },
  { name: "Horizon Zero Dawn", category: "action", description: "An open-world action game with robotic creatures.", howToPlay: "Hunt robotic creatures and uncover the world’s secrets." },
  { name: "Metal Gear Solid V", category: "action", description: "A stealth-action game with open-world elements.", howToPlay: "Complete missions with stealth or combat in a dynamic world." },
  { name: "Bayonetta 2", category: "action", description: "A stylish hack-and-slash action game.", howToPlay: "Use combos and magical attacks to defeat enemies." },
  { name: "Devil May Cry 5", category: "action", description: "A fast-paced action game with stylish combat.", howToPlay: "Control characters with unique weapons and fight demons." },
  { name: "Sekiro: Shadows Die Twice", category: "action", description: "A challenging action game with stealth elements.", howToPlay: "Use precise timing and tactics to defeat powerful foes." },
  { name: "Nioh 2", category: "action", description: "An action game set in a fantastical version of Japan's Sengoku era.", howToPlay: "Fight enemies with samurai skills and unlock new abilities." },
  { name: "The Evil Within 2", category: "action", description: "A horror-action game with a twisted narrative.", howToPlay: "Survive horrifying encounters and solve mysteries." },
  { name: "Dishonored 2", category: "action", description: "A stealth-action game with magical powers.", howToPlay: "Choose stealth or combat to complete objectives." },
  { name: "Dying Light", category: "action", description: "A zombie survival action game with parkour mechanics.", howToPlay: "Explore the city, complete missions, and fight or evade zombies." },
  { name: "State of Decay 2", category: "action", description: "A zombie survival action game with base-building.", howToPlay: "Manage resources, build your base, and survive the apocalypse." },
  { name: "Borderlands 3", category: "action", description: "A looter-shooter action game.", howToPlay: "Explore planets, collect loot, and defeat enemies with unique weapons." },
  { name: "Saints Row IV", category: "action", description: "An open-world action game with superpowers.", howToPlay: "Complete over-the-top missions with chaotic gameplay." },
  { name: "Infamous: Second Son", category: "action", description: "An open-world superhero action game.", howToPlay: "Use superpowers to fight enemies or explore the city." },
  { name: "Quantum Break", category: "action", description: "A third-person action game with time-manipulation powers.", howToPlay: "Fight enemies using firearms and time-bending abilities." },
  { name: "The Saboteur", category: "action", description: "An open-world action game set in WWII France.", howToPlay: "Sabotage Nazi forces and liberate Paris." },
  { name: "Red Faction: Guerrilla", category: "action", description: "An open-world action game with destructible environments.", howToPlay: "Fight enemies using weapons and environmental destruction." },
  { name: "Prototype 2", category: "action", description: "A superhuman action game.", howToPlay: "Use bio-weapons and superpowers to defeat enemies." },
  { name: "Crysis 3", category: "action", description: "A first-person shooter with high-tech abilities.", howToPlay: "Use advanced technology and weapons to complete missions." },
  { name: "Bulletstorm", category: "action", description: "A high-energy first-person shooter.", howToPlay: "Use creative kills to score points in a chaotic environment." },
  { name: "Spec Ops: The Line", category: "action", description: "A third-person shooter with a powerful story.", howToPlay: "Complete missions and make moral decisions in a war-torn city." },
  { name: "L.A. Noire", category: "action", description: "An action game focused on solving crimes in 1940s LA.", howToPlay: "Investigate crime scenes, interrogate suspects, and solve cases." },
  { name: "Wolfenstein: The New Order", category: "action", description: "A first-person shooter with a WWII alternate history theme.", howToPlay: "Fight against Nazi forces using weapons and tactics." },
  { name: "Prey (2017)", category: "action", description: "A first-person action game set in a space station.", howToPlay: "Survive against aliens and uncover the station’s mysteries." },
  { name: "Rage 2", category: "action", description: "An open-world first-person shooter.", howToPlay: "Fight enemies and explore a post-apocalyptic wasteland." },
  { name: "Sniper Elite 4", category: "action", description: "A tactical third-person shooter.", howToPlay: "Complete missions by sniping enemies from long distances." },
  { name: "Black Mesa", category: "action", description: "A remake of the classic Half-Life game.", howToPlay: "Survive and solve puzzles in a sci-fi setting." },
  { name: "Vanquish", category: "action", description: "A fast-paced third-person shooter.", howToPlay: "Use advanced technology to defeat robotic enemies." },
  { name: "Dead Island", category: "action", description: "A zombie action game set on a tropical island.", howToPlay: "Survive zombie hordes, complete missions, and upgrade weapons." },
  { name: "Homefront: The Revolution", category: "action", description: "An open-world first-person shooter.", howToPlay: "Liberate a city occupied by enemy forces through guerrilla warfare." },
  { name: "Max Payne 3", category: "action", description: "A third-person shooter with a cinematic narrative.", howToPlay: "Fight enemies using bullet-time mechanics." }
);

games.push(
  { name: "League of Legends", category: "moba", description: "A popular MOBA game with diverse champions and competitive gameplay.", howToPlay: "Work with your team to destroy the enemy's Nexus." },
  { name: "Dota 2", category: "moba", description: "A highly strategic MOBA game with complex mechanics.", howToPlay: "Choose a hero, level up, and destroy the enemy’s Ancient." },
  { name: "Smite", category: "moba", description: "A third-person MOBA with gods and mythology-inspired characters.", howToPlay: "Compete in team battles to destroy the enemy's base." },
  { name: "Mobile Legends: Bang Bang", category: "moba", description: "A mobile MOBA with fast-paced 5v5 battles.", howToPlay: "Pick a hero and work with your team to dominate the enemy." },
  { name: "Arena of Valor", category: "moba", description: "A mobile MOBA game with multiple game modes.", howToPlay: "Fight in team battles and destroy enemy towers." },
  { name: "Heroes of the Storm", category: "moba", description: "A Blizzard MOBA with iconic characters from their franchises.", howToPlay: "Work with your team to achieve objectives and win the match." },
  { name: "Wild Rift", category: "moba", description: "A mobile version of League of Legends with faster matches.", howToPlay: "Battle in 5v5 matches and aim to destroy the Nexus." },
  { name: "Vainglory", category: "moba", description: "A visually stunning MOBA optimized for touch controls.", howToPlay: "Team up and destroy the enemy's crystal in intense battles." },
  { name: "Paladins Strike", category: "moba", description: "A MOBA spin-off of the popular shooter Paladins.", howToPlay: "Use hero abilities and strategy to win matches." },
  { name: "Battlerite", category: "moba", description: "A fast-paced MOBA with a focus on skill-based combat.", howToPlay: "Engage in arena battles with unique champions." },
  { name: "Strife", category: "moba", description: "A MOBA that simplifies gameplay while focusing on teamwork.", howToPlay: "Destroy enemy towers and work towards victory with your team." },
  { name: "Paragon", category: "moba", description: "A third-person MOBA with stunning graphics.", howToPlay: "Team up with others to destroy the enemy's core." },
  { name: "Gigantic", category: "moba", description: "A MOBA with unique, large guardians aiding your team.", howToPlay: "Protect your guardian and eliminate the enemy's guardian." },
  { name: "Heroes of Newerth", category: "moba", description: "A classic MOBA with a loyal community.", howToPlay: "Choose a hero and work with your team to outplay opponents." },
  { name: "Prime World", category: "moba", description: "A MOBA that blends strategy and RPG mechanics.", howToPlay: "Capture territory and defeat the enemy's team." },
  { name: "Awesomenauts", category: "moba", description: "A 2D platformer MOBA with colorful characters.", howToPlay: "Engage in team battles and destroy enemy turrets." },
  { name: "Supernova", category: "moba", description: "A sci-fi MOBA with customizable units.", howToPlay: "Fight alongside your team and upgrade your forces." },
  { name: "AirMech", category: "moba", description: "A futuristic MOBA with real-time strategy elements.", howToPlay: "Control your AirMech and command units to victory." },
  { name: "Eternal Return", category: "moba", description: "A MOBA-Battle Royale hybrid.", howToPlay: "Survive against other players and secure objectives to win." },
  { name: "Master X Master", category: "moba", description: "A MOBA with tag-team mechanics.", howToPlay: "Control two heroes and switch between them in battle." },
  { name: "Genesis", category: "moba", description: "A console-exclusive MOBA with immersive visuals.", howToPlay: "Work with your team to destroy the enemy base." },
  { name: "Core Masters", category: "moba", description: "A fast-paced MOBA focused on capturing objectives.", howToPlay: "Control the map by capturing and defending cores." },
  { name: "Infinite Crisis", category: "moba", description: "A DC Comics-themed MOBA.", howToPlay: "Control iconic DC heroes and villains to defeat your enemies." },
  { name: "Fates Forever", category: "moba", description: "A tablet-focused MOBA with unique mechanics.", howToPlay: "Compete in team battles and secure victory by destroying objectives." },
  { name: "Rise of Immortals", category: "moba", description: "A MOBA with persistent character progression.", howToPlay: "Choose an immortal and lead your team to victory." },
  { name: "Heavy Metal Machines", category: "moba", description: "A vehicle-based MOBA with fast-paced action.", howToPlay: "Control vehicles and defeat enemies in explosive battles." },
  { name: "Shards of War", category: "moba", description: "A sci-fi-themed MOBA with WASD controls.", howToPlay: "Battle in a futuristic world and secure objectives." },
  { name: "Trans-Galactic Tournament", category: "moba", description: "A MOBA with colorful characters and quick matches.", howToPlay: "Fight with your team in a fast-paced arena." },
  { name: "Fractured Space", category: "moba", description: "A space-themed MOBA with massive ships.", howToPlay: "Command your fleet and outmaneuver your opponents." },
  { name: "Heroes Evolved", category: "moba", description: "A classic MOBA with a variety of heroes.", howToPlay: "Fight in team battles and secure victory by destroying the base." },
  { name: "Mobile Battleground: Frontline", category: "moba", description: "A mobile MOBA with short match times.", howToPlay: "Compete in 3v3 or 5v5 battles and achieve victory." },
  { name: "Onmyoji Arena", category: "moba", description: "A MOBA based on the Onmyoji universe.", howToPlay: "Control Shikigami heroes in strategic battles." },
  { name: "MOBA Legends", category: "moba", description: "A fast-paced mobile MOBA.", howToPlay: "Choose a hero and lead your team to victory in short matches." },
  { name: "Light x Shadow", category: "moba", description: "A mobile MOBA with anime-inspired characters.", howToPlay: "Fight in 5v5 battles and upgrade your heroes." },
  { name: "Soul of Eden", category: "moba", description: "A card-based MOBA with real-time combat.", howToPlay: "Deploy cards to control the battlefield and secure objectives." },
  { name: "MOBA Duels", category: "moba", description: "A fast-paced MOBA with card mechanics.", howToPlay: "Strategically use cards to control heroes and win battles." },
  { name: "Ace of Arenas", category: "moba", description: "A mobile MOBA with competitive gameplay.", howToPlay: "Battle enemies in the arena and climb the ranks." },
  { name: "Extraordinary Ones", category: "moba", description: "A MOBA with a high school anime theme.", howToPlay: "Choose a student-hero and lead your team to victory." },
  { name: "Cat Quest: Arena", category: "moba", description: "A MOBA with feline characters.", howToPlay: "Control cats in an arena and fight for dominance." },
  { name: "Overdox", category: "moba", description: "A hybrid MOBA with melee combat.", howToPlay: "Fight enemies in real-time and secure the battlefield." },
  { name: "Dungeon Hunter Champions", category: "moba", description: "A MOBA with a mix of RPG elements.", howToPlay: "Assemble a team and fight battles in a fantasy world." },
  { name: "Mobile MOBA", category: "moba", description: "A fast and light MOBA experience.", howToPlay: "Battle enemies and use unique abilities to win." },
  { name: "MOBA Wars", category: "moba", description: "A futuristic MOBA.", howToPlay: "Destroy the enemy's core while defending your own." },
  { name: "Hero Hunters MOBA", category: "moba", description: "A hybrid MOBA and hero shooter.", howToPlay: "Control heroes and compete in fast-paced battles." },
  { name: "Iron League", category: "moba", description: "A mobile MOBA with team-based gameplay.", howToPlay: "Team up to fight and dominate the battlefield." }
);

games.push(
  { name: "Pac-Man", category: "arcade", description: "A classic arcade game where you eat pellets and avoid ghosts.", howToPlay: "Navigate the maze, eat all the pellets, and avoid the ghosts." },
  { name: "Space Invaders", category: "arcade", description: "An iconic arcade shooter game.", howToPlay: "Shoot the alien invaders before they reach your base." },
  { name: "Donkey Kong", category: "arcade", description: "A platform arcade game featuring Mario.", howToPlay: "Climb ladders and dodge obstacles to rescue the princess." },
  { name: "Galaga", category: "arcade", description: "A classic space shooter game.", howToPlay: "Destroy enemy ships while avoiding their attacks." },
  { name: "Asteroids", category: "arcade", description: "A space-themed shooter game.", howToPlay: "Shoot asteroids and avoid being hit by debris." },
  { name: "Frogger", category: "arcade", description: "A game where you guide a frog across roads and rivers.", howToPlay: "Safely navigate your frog to its home without getting hit." },
  { name: "Tetris", category: "arcade", description: "A timeless block-stacking puzzle game.", howToPlay: "Arrange falling blocks to create complete lines and score points." },
  { name: "Street Fighter II", category: "arcade", description: "A classic arcade fighting game.", howToPlay: "Choose a fighter and defeat opponents in one-on-one battles." },
  { name: "Mortal Kombat", category: "arcade", description: "A brutal arcade fighting game.", howToPlay: "Use special moves and combos to defeat opponents." },
  { name: "Centipede", category: "arcade", description: "A fast-paced arcade shooter.", howToPlay: "Destroy the centipede before it reaches the bottom of the screen." },
  { name: "Bubble Bobble", category: "arcade", description: "A cute bubble-shooting platform game.", howToPlay: "Capture enemies in bubbles and pop them to clear levels." },
  { name: "Paperboy", category: "arcade", description: "An arcade game where you deliver newspapers.", howToPlay: "Deliver newspapers to subscribers while avoiding obstacles." },
  { name: "Rampage", category: "arcade", description: "An arcade game where you control monsters destroying cities.", howToPlay: "Smash buildings and fight enemies as a giant monster." },
  { name: "Q*bert", category: "arcade", description: "A platform arcade game with a hopping character.", howToPlay: "Change the colors of blocks while avoiding enemies." },
  { name: "Dig Dug", category: "arcade", description: "A game where you dig tunnels and defeat enemies underground.", howToPlay: "Pump up enemies or crush them with rocks." },
  { name: "Ms. Pac-Man", category: "arcade", description: "A sequel to Pac-Man with new mazes and gameplay.", howToPlay: "Eat pellets, avoid ghosts, and collect fruit for bonus points." },
  { name: "Pole Position", category: "arcade", description: "A racing arcade game.", howToPlay: "Complete laps and finish first while avoiding crashes." },
  { name: "Crazy Taxi", category: "arcade", description: "An arcade driving game where you transport passengers.", howToPlay: "Pick up passengers and deliver them to their destinations quickly." },
  { name: "Golden Axe", category: "arcade", description: "A side-scrolling beat-em-up arcade game.", howToPlay: "Fight enemies using weapons and magic in a fantasy setting." },
  { name: "Gauntlet", category: "arcade", description: "A dungeon-crawling arcade game.", howToPlay: "Choose a character and battle through mazes of enemies." },
  { name: "Joust", category: "arcade", description: "A game where you ride a flying ostrich in combat.", howToPlay: "Defeat enemy knights by colliding with them from above." },
  { name: "Time Crisis", category: "arcade", description: "An arcade shooter with a light gun.", howToPlay: "Shoot enemies and use cover to avoid being hit." },
  { name: "Track and Field", category: "arcade", description: "A sports arcade game with Olympic events.", howToPlay: "Compete in events like running, jumping, and throwing." },
  { name: "1942", category: "arcade", description: "A WWII-themed top-down shooter.", howToPlay: "Control your aircraft and destroy enemy planes." },
  { name: "Altered Beast", category: "arcade", description: "A side-scrolling beat-em-up game.", howToPlay: "Transform into beasts and fight your way through levels." },
  { name: "Moon Patrol", category: "arcade", description: "A side-scrolling shooter set on the moon.", howToPlay: "Jump over obstacles and shoot enemies in your moon buggy." },
  { name: "Punch-Out!!", category: "arcade", description: "A boxing arcade game.", howToPlay: "Defeat opponents using well-timed punches and dodges." },
  { name: "Double Dragon", category: "arcade", description: "A co-op beat-em-up arcade game.", howToPlay: "Fight enemies and rescue your kidnapped girlfriend." },
  { name: "Contra", category: "arcade", description: "A classic run-and-gun arcade game.", howToPlay: "Defeat enemies and bosses in fast-paced combat." },
  { name: "Super Hang-On", category: "arcade", description: "A motorcycle racing arcade game.", howToPlay: "Race through checkpoints and beat the timer." },
  { name: "Out Run", category: "arcade", description: "A classic arcade driving game.", howToPlay: "Race through scenic locations and avoid traffic." },
  { name: "Spy Hunter", category: "arcade", description: "A vehicle combat arcade game.", howToPlay: "Destroy enemy vehicles while avoiding hazards." },
  { name: "The Simpsons Arcade Game", category: "arcade", description: "A beat-em-up game featuring The Simpsons.", howToPlay: "Fight enemies as your favorite Simpsons characters." },
  { name: "Teenage Mutant Ninja Turtles: The Arcade Game", category: "arcade", description: "A co-op beat-em-up arcade game.", howToPlay: "Fight enemies and save April O'Neil." },
  { name: "Marvel vs. Capcom 2", category: "arcade", description: "A crossover fighting game.", howToPlay: "Choose your team and battle opponents in 2D combat." },
  { name: "Dragon's Lair", category: "arcade", description: "An animated adventure arcade game.", howToPlay: "Follow prompts to guide Dirk the Daring to victory." },
  { name: "Robotron: 2084", category: "arcade", description: "A twin-stick shooter arcade game.", howToPlay: "Rescue humans while defeating robots in chaotic action." },
  { name: "Defender", category: "arcade", description: "A side-scrolling shooter arcade game.", howToPlay: "Protect humans from alien abduction while destroying enemies." },
  { name: "Xevious", category: "arcade", description: "A top-down arcade shooter.", howToPlay: "Control a fighter jet and destroy ground and air targets." },
  { name: "Tempest", category: "arcade", description: "A vector-based arcade shooter.", howToPlay: "Shoot enemies and avoid obstacles in a tube-like setting." },
  { name: "Star Wars Arcade", category: "arcade", description: "An arcade game based on the Star Wars franchise.", howToPlay: "Pilot a starfighter and destroy enemy ships." },
  { name: "Arkanoid", category: "arcade", description: "A block-breaking arcade game.", howToPlay: "Bounce the ball to break all blocks on the screen." },
  { name: "R-Type", category: "arcade", description: "A side-scrolling shooter arcade game.", howToPlay: "Control a spaceship and defeat waves of enemies." },
  { name: "Zaxxon", category: "arcade", description: "An isometric shooter arcade game.", howToPlay: "Fly your spaceship and destroy enemy targets." },
  { name: "Kung-Fu Master", category: "arcade", description: "A martial arts beat-em-up game.", howToPlay: "Fight through enemies to rescue your kidnapped girlfriend." },
  { name: "Snow Bros", category: "arcade", description: "A platform arcade game with snowball-throwing characters.", howToPlay: "Defeat enemies by turning them into snowballs." },
  { name: "BurgerTime", category: "arcade", description: "A platform arcade game where you assemble burgers.", howToPlay: "Avoid enemies while building burgers layer by layer." }
);

games.push(
  { name: "Typing of the Dead", category: "educational", description: "A typing-based game to improve typing speed.", howToPlay: "Type words quickly to defeat zombies." },
  { name: "Reader Rabbit", category: "educational", description: "A classic game focused on reading and phonics.", howToPlay: "Complete reading and puzzle challenges to progress." },
  { name: "Math Blaster", category: "educational", description: "A math-focused game that blends learning with action.", howToPlay: "Solve math problems to save the galaxy." },
  { name: "Oregon Trail", category: "educational", description: "A game that teaches historical and survival skills.", howToPlay: "Lead your wagon party to Oregon, managing resources and challenges." },
  { name: "Where in the World is Carmen Sandiego?", category: "educational", description: "A geography game about finding a thief.", howToPlay: "Follow clues to track Carmen around the globe." },
  { name: "JumpStart Adventures", category: "educational", description: "A series of educational games for kids.", howToPlay: "Solve puzzles and complete activities to learn new skills." },
  { name: "Zoombinis", category: "educational", description: "A logic game with adorable characters.", howToPlay: "Solve puzzles to help the Zoombinis reach their new home." },
  { name: "Duolingo ABC", category: "educational", description: "A language learning game for kids.", howToPlay: "Learn basic words and phrases through interactive lessons." },
  { name: "Brain Age", category: "educational", description: "A game to keep your mind sharp with daily exercises.", howToPlay: "Complete puzzles, math problems, and memory games." },
  { name: "Typing Club", category: "educational", description: "A typing tutorial game.", howToPlay: "Complete levels by typing accurately and quickly." },
  { name: "Code Combat", category: "educational", description: "A coding game where you learn programming by playing.", howToPlay: "Write code to control your character and solve challenges." },
  { name: "Prodigy Math Game", category: "educational", description: "A math RPG for kids.", howToPlay: "Solve math problems to defeat enemies and level up." },
  { name: "ScratchJr", category: "educational", description: "A beginner coding game for young children.", howToPlay: "Drag and drop blocks to create animations and stories." },
  { name: "Lightbot", category: "educational", description: "A game that teaches programming logic.", howToPlay: "Program a robot to navigate levels using code-like commands." },
  { name: "Stack the States", category: "educational", description: "A geography game about U.S. states.", howToPlay: "Answer trivia to earn and stack states to complete levels." },
  { name: "Monument Valley", category: "educational", description: "A game that teaches spatial reasoning through puzzles.", howToPlay: "Guide your character through optical illusions and mazes." },
  { name: "Kerbal Space Program", category: "educational", description: "A physics-based game about space exploration.", howToPlay: "Build rockets and explore planets while learning orbital mechanics." },
  { name: "DragonBox Algebra", category: "educational", description: "A game that teaches algebra concepts.", howToPlay: "Solve puzzles that gradually introduce algebraic equations." },
  { name: "Lumosity", category: "educational", description: "A game platform for cognitive training.", howToPlay: "Play games designed to improve memory, attention, and problem-solving." },
  { name: "ChessKid", category: "educational", description: "A chess game aimed at teaching strategy.", howToPlay: "Learn chess moves and tactics while playing against others." },
  { name: "Spelling City", category: "educational", description: "A spelling game for kids.", howToPlay: "Complete word games and spelling challenges to improve vocabulary." },
  { name: "ABCmouse", category: "educational", description: "A comprehensive educational app for young children.", howToPlay: "Complete lessons in reading, math, and science to earn rewards." },
  { name: "Kahoot!", category: "educational", description: "A quiz-based learning game.", howToPlay: "Answer questions quickly to score points and beat other players." },
  { name: "Minecraft: Education Edition", category: "educational", description: "An educational version of Minecraft.", howToPlay: "Learn coding, math, and teamwork through structured challenges." },
  { name: "Gravity Simulator", category: "educational", description: "A physics-based game about gravity.", howToPlay: "Experiment with gravity and orbits to solve puzzles." },
  { name: "Roblox Education Games", category: "educational", description: "Educational games made within Roblox.", howToPlay: "Explore worlds designed to teach coding, math, and problem-solving." },
  { name: "Adventure Academy", category: "educational", description: "An educational MMORPG for kids.", howToPlay: "Complete lessons and quests to learn new subjects." },
  { name: "Typing Rocket", category: "educational", description: "A typing game with rockets and explosions.", howToPlay: "Type the words quickly to launch rockets and earn points." },
  { name: "Physics Playground", category: "educational", description: "A game to explore physics principles.", howToPlay: "Experiment with forces, gravity, and motion to complete tasks." },
  { name: "Slice Fractions", category: "educational", description: "A math game focused on fractions.", howToPlay: "Solve fraction puzzles to progress through levels." },
  { name: "PBS Kids Games", category: "educational", description: "A collection of educational games for children.", howToPlay: "Play games that teach science, math, and literacy." },
  { name: "GeoGuessr", category: "educational", description: "A geography game based on Google Maps.", howToPlay: "Guess the location based on Street View images." },
  { name: "Scribblenauts", category: "educational", description: "A creative problem-solving game.", howToPlay: "Use your imagination to solve puzzles by summoning objects." },
  { name: "BrainPOP GameUp", category: "educational", description: "Educational games covering multiple subjects.", howToPlay: "Complete subject-specific games to reinforce learning." },
  { name: "DragonBox Numbers", category: "educational", description: "A math game for young learners.", howToPlay: "Solve puzzles to learn basic numbers and operations." },
  { name: "Learn to Code with Swift", category: "educational", description: "A game to teach Apple's Swift programming language.", howToPlay: "Write Swift code to guide characters through puzzles." },
  { name: "National Geographic Kids", category: "educational", description: "Interactive games about nature and science.", howToPlay: "Complete challenges while learning about animals and geography." },
  { name: "Duolingo", category: "educational", description: "A language learning app with gamified lessons.", howToPlay: "Complete lessons and quizzes to learn a new language." },
  { name: "Little Alchemy", category: "educational", description: "A game about creating new elements.", howToPlay: "Combine basic elements to discover new ones." },
  { name: "Codemonkey", category: "educational", description: "A coding game that teaches JavaScript.", howToPlay: "Write code to solve puzzles and guide your character." },
  { name: "Rosetta Stone Kids", category: "educational", description: "A language learning app for children.", howToPlay: "Learn basic phrases through interactive games." },
  { name: "Elevate", category: "educational", description: "A brain training app for adults.", howToPlay: "Complete exercises to improve communication and analytical skills." },
  { name: "Star Walk Kids", category: "educational", description: "An astronomy app for children.", howToPlay: "Learn about constellations and planets through exploration." },
  { name: "MobyMax", category: "educational", description: "A comprehensive learning platform for kids.", howToPlay: "Complete lessons and earn rewards for progress." },
  { name: "Learn to Count 123", category: "educational", description: "A counting game for preschoolers.", howToPlay: "Count objects and match numbers to learn basic math." },
  { name: "Science Max", category: "educational", description: "A science-focused educational game.", howToPlay: "Solve experiments and learn scientific concepts." },
  { name: "Coolmath Games", category: "educational", description: "A collection of math-based games.", howToPlay: "Solve puzzles and complete levels to improve math skills." }
);

games.push(
  { name: "Super Mario Bros.", category: "platformer", description: "A classic platformer featuring Mario and Luigi.", howToPlay: "Jump over obstacles and defeat enemies to save the princess." },
  { name: "Sonic the Hedgehog", category: "platformer", description: "A fast-paced platformer starring Sonic.", howToPlay: "Collect rings, defeat enemies, and save animals from Dr. Robotnik." },
  { name: "Celeste", category: "platformer", description: "A challenging platformer about climbing a mountain.", howToPlay: "Navigate challenging levels and discover the story of Madeline." },
  { name: "Hollow Knight", category: "platformer", description: "An atmospheric platformer set in a bug kingdom.", howToPlay: "Explore the world, defeat enemies, and uncover secrets." },
  { name: "Ori and the Blind Forest", category: "platformer", description: "A visually stunning platformer with a heartfelt story.", howToPlay: "Guide Ori through puzzles and enemies to restore the forest." },
  { name: "Rayman Legends", category: "platformer", description: "A whimsical platformer with creative levels.", howToPlay: "Jump, run, and punch through beautifully designed stages." },
  { name: "Donkey Kong Country", category: "platformer", description: "A classic platformer featuring Donkey Kong.", howToPlay: "Collect bananas and defeat enemies to progress through levels." },
  { name: "Cuphead", category: "platformer", description: "A 1930s cartoon-style platformer with boss battles.", howToPlay: "Shoot, dodge, and defeat bosses in challenging levels." },
  { name: "Crash Bandicoot", category: "platformer", description: "A platformer featuring the wacky Crash Bandicoot.", howToPlay: "Spin and jump through colorful, obstacle-filled levels." },
  { name: "Limbo", category: "platformer", description: "A dark, atmospheric puzzle-platformer.", howToPlay: "Solve puzzles and avoid traps in a mysterious black-and-white world." },
  { name: "Inside", category: "platformer", description: "A story-driven platformer with a dystopian theme.", howToPlay: "Solve environmental puzzles to uncover the game's secrets." },
  { name: "Fez", category: "platformer", description: "A puzzle-platformer with a unique 2D-to-3D mechanic.", howToPlay: "Rotate the world to solve puzzles and explore." },
  { name: "Mega Man", category: "platformer", description: "A classic action-platformer featuring Mega Man.", howToPlay: "Defeat robot masters and gain their abilities." },
  { name: "Shovel Knight", category: "platformer", description: "A retro-inspired platformer with shovel combat.", howToPlay: "Use your shovel to defeat enemies and uncover treasure." },
  { name: "Banjo-Kazooie", category: "platformer", description: "A 3D platformer with a bear and bird duo.", howToPlay: "Collect items and solve puzzles to progress through vibrant worlds." },
  { name: "A Hat in Time", category: "platformer", description: "A cute 3D platformer with creative levels.", howToPlay: "Explore whimsical worlds and collect time pieces." },
  { name: "Braid", category: "platformer", description: "A puzzle-platformer with time manipulation mechanics.", howToPlay: "Rewind time to solve puzzles and progress through the story." },
  { name: "Little Nightmares", category: "platformer", description: "A horror-themed platformer with eerie visuals.", howToPlay: "Avoid monsters and escape a haunting, surreal world." },
  { name: "Spelunky", category: "platformer", description: "A roguelike platformer with procedurally generated levels.", howToPlay: "Explore caves, collect treasure, and avoid deadly traps." },
  { name: "Super Meat Boy", category: "platformer", description: "A fast-paced, precision platformer.", howToPlay: "Guide Meat Boy through challenging, obstacle-filled levels." },
  { name: "Terraria", category: "platformer", description: "A sandbox platformer with crafting and exploration.", howToPlay: "Build, mine, and fight through a procedurally generated world." },
  { name: "VVVVVV", category: "platformer", description: "A gravity-flipping platformer.", howToPlay: "Flip gravity to navigate challenging levels." },
  { name: "Unravel", category: "platformer", description: "A puzzle-platformer featuring a yarn character.", howToPlay: "Solve puzzles and explore using the character's yarn abilities." },
  { name: "Thomas Was Alone", category: "platformer", description: "A minimalist platformer with a focus on storytelling.", howToPlay: "Control shapes with unique abilities to progress." },
  { name: "Kirby's Adventure", category: "platformer", description: "A platformer starring Kirby with unique copy abilities.", howToPlay: "Swallow enemies and use their powers to defeat bosses." },
  { name: "Yoshi's Island", category: "platformer", description: "A colorful platformer with Yoshi as the main character.", howToPlay: "Carry Baby Mario safely through levels and solve puzzles." },
  { name: "Metroid Dread", category: "platformer", description: "A sci-fi platformer with exploration and combat.", howToPlay: "Explore alien worlds, collect upgrades, and defeat enemies." },
  { name: "Trine", category: "platformer", description: "A fantasy platformer with three unique characters.", howToPlay: "Switch between characters to solve puzzles and fight enemies." },
  { name: "LIMBO", category: "platformer", description: "A dark platformer with minimalistic art.", howToPlay: "Guide a boy through dangerous environments." },
  { name: "Oddworld: Abe's Oddysee", category: "platformer", description: "A cinematic platformer with puzzle elements.", howToPlay: "Guide Abe through dangers while saving his friends." },
  { name: "Katana ZERO", category: "platformer", description: "A neon-noir platformer with fast-paced combat.", howToPlay: "Slash and strategize to defeat enemies in stylish levels." },
  { name: "Cave Story", category: "platformer", description: "A story-rich platformer with exploration.", howToPlay: "Discover secrets, fight enemies, and save a village." },
  { name: "Super Lucky's Tale", category: "platformer", description: "A 3D platformer starring Lucky the fox.", howToPlay: "Run, jump, and dig through fun-filled levels." },
  { name: "Rogue Legacy", category: "platformer", description: "A roguelike platformer with generational heroes.", howToPlay: "Explore dungeons and upgrade your lineage." },
  { name: "Axiom Verge", category: "platformer", description: "A sci-fi platformer with exploration and upgrades.", howToPlay: "Discover a strange world and use weapons to defeat enemies." },
  { name: "Grow Home", category: "platformer", description: "A physics-based platformer with climbing mechanics.", howToPlay: "Guide a robot to grow a plant and reach your ship." },
  { name: "Dead Cells", category: "platformer", description: "A roguelike platformer with combat and exploration.", howToPlay: "Fight enemies and discover upgrades in procedurally generated levels." },
  { name: "Toki Tori", category: "platformer", description: "A puzzle-platformer featuring a cute chick.", howToPlay: "Solve puzzles to collect eggs in each level." },
  { name: "Spyro Reignited Trilogy", category: "platformer", description: "A remastered version of the classic Spyro games.", howToPlay: "Explore colorful worlds and collect gems as Spyro." },
  { name: "Giana Sisters: Twisted Dreams", category: "platformer", description: "A platformer with a dual-world mechanic.", howToPlay: "Switch between dreams to solve puzzles and defeat enemies." },
  { name: "Freedom Planet", category: "platformer", description: "A fast-paced platformer inspired by classic Sonic games.", howToPlay: "Defeat enemies and bosses while exploring colorful levels." },
  { name: "Super Tux", category: "platformer", description: "A platformer featuring Tux the penguin.", howToPlay: "Run and jump through levels while collecting items." },
  { name: "Iconoclasts", category: "platformer", description: "A story-driven platformer with puzzles and combat.", howToPlay: "Solve mechanical puzzles and defeat enemies to progress." },
  { name: "DuckTales Remastered", category: "platformer", description: "A remastered version of the classic DuckTales game.", howToPlay: "Collect treasures and defeat enemies as Scrooge McDuck." },
  { name: "New Super Mario Bros. U Deluxe", category: "platformer", description: "A modern take on the classic Mario platformers.", howToPlay: "Guide Mario through levels to save Princess Peach." },
);

games.push(
  { name: "Trivia Crack", category: "trivia/quiz", description: "A fun multiplayer trivia game.", howToPlay: "Answer questions from various categories to beat your opponent." },
  { name: "QuizUp", category: "trivia/quiz", description: "A social trivia game with thousands of topics.", howToPlay: "Compete in real-time trivia matches on your favorite topics." },
  { name: "Jeopardy! World Tour", category: "trivia/quiz", description: "A mobile adaptation of the classic TV game show.", howToPlay: "Answer trivia questions and wager wisely to win." },
  { name: "Who Wants to Be a Millionaire?", category: "trivia/quiz", description: "A trivia game based on the famous TV show.", howToPlay: "Answer increasingly difficult questions to win virtual money." },
  { name: "HQ Trivia", category: "trivia/quiz", description: "A live trivia game show.", howToPlay: "Answer questions in real-time for a chance to win prizes." },
  { name: "Kahoot!", category: "trivia/quiz", description: "An interactive quiz platform for education and fun.", howToPlay: "Answer questions quickly to earn points and win." },
  { name: "Quiz Planet", category: "trivia/quiz", description: "A multiplayer trivia game.", howToPlay: "Challenge friends and answer questions in various categories." },
  { name: "The Impossible Quiz", category: "trivia/quiz", description: "A humorous and challenging trivia game.", howToPlay: "Answer trick questions and think outside the box." },
  { name: "PopcornTrivia", category: "trivia/quiz", description: "A trivia game focused on movies and TV shows.", howToPlay: "Answer questions about your favorite films and shows." },
  { name: "SongPop", category: "trivia/quiz", description: "A music trivia game.", howToPlay: "Guess song titles and artists faster than your opponent." },
  { name: "Logo Quiz", category: "trivia/quiz", description: "A game about identifying logos.", howToPlay: "Guess the names of companies and brands from their logos." },
  { name: "Trivial Pursuit Live!", category: "trivia/quiz", description: "A digital version of the classic board game.", howToPlay: "Answer questions from various categories to win wedges." },
  { name: "Family Feud Live!", category: "trivia/quiz", description: "A trivia game based on the TV show.", howToPlay: "Guess the most popular answers to survey questions." },
  { name: "Sporkle", category: "trivia/quiz", description: "An online trivia game with a variety of quizzes.", howToPlay: "Complete quizzes in categories like geography, history, and pop culture." },
  { name: "Guess the Emoji", category: "trivia/quiz", description: "A trivia game about interpreting emoji combinations.", howToPlay: "Guess the phrase or word represented by the emojis." },
  { name: "Quizoid", category: "trivia/quiz", description: "An offline trivia game with a variety of questions.", howToPlay: "Answer trivia questions in different categories to score points." },
  { name: "Evil Apples", category: "trivia/quiz", description: "A humorous card-based trivia game.", howToPlay: "Choose the funniest answer to match the question card." },
  { name: "Brain Test: Tricky Puzzles", category: "trivia/quiz", description: "A quiz game with tricky and humorous questions.", howToPlay: "Think creatively to solve the puzzles and quizzes." },
  { name: "Psych!", category: "trivia/quiz", description: "A multiplayer trivia game with bluffing.", howToPlay: "Create fake answers to fool others while guessing the correct one." },
  { name: "Gartic Phone", category: "trivia/quiz", description: "A drawing and guessing game.", howToPlay: "Guess phrases based on drawings in a group setting." },
  { name: "Millionaire Trivia: TV Game", category: "trivia/quiz", description: "A trivia game modeled after 'Who Wants to Be a Millionaire?'", howToPlay: "Answer questions and use lifelines to climb the prize ladder." },
  { name: "True or False", category: "trivia/quiz", description: "A quick trivia game with true or false questions.", howToPlay: "Decide whether each statement is true or false." },
  { name: "The Chase", category: "trivia/quiz", description: "A quiz game based on the popular UK TV show.", howToPlay: "Answer questions to outrun the Chaser." },
  { name: "iAssociate 2", category: "trivia/quiz", description: "A word association quiz game.", howToPlay: "Connect words based on their relationships." },
  { name: "Quiz RPG: World of Mystic Wiz", category: "trivia/quiz", description: "A trivia game combined with RPG elements.", howToPlay: "Answer questions to cast spells and defeat enemies." },
  { name: "Quiz Clash", category: "trivia/quiz", description: "A competitive quiz game.", howToPlay: "Answer questions in a timed match against friends or strangers." },
  { name: "Knowledge is Power", category: "trivia/quiz", description: "A family-friendly trivia game.", howToPlay: "Answer trivia questions and sabotage opponents to win." },
  { name: "Fact or Fiction", category: "trivia/quiz", description: "A trivia game about separating truth from lies.", howToPlay: "Decide whether each statement is fact or fiction." },
  { name: "Quiplash", category: "trivia/quiz", description: "A humorous multiplayer quiz game.", howToPlay: "Write funny answers to prompts and vote for the best ones." },
  { name: "Quiz Battle", category: "trivia/quiz", description: "A fast-paced trivia game.", howToPlay: "Answer rapid-fire questions to defeat opponents." },
  { name: "Guess Their Answer", category: "trivia/quiz", description: "A trivia game about popular answers.", howToPlay: "Guess the most common responses to questions." },
  { name: "10 Questions!", category: "trivia/quiz", description: "A short trivia game.", howToPlay: "Answer 10 random questions as quickly as possible." },
  { name: "Guess the Picture", category: "trivia/quiz", description: "A trivia game with picture clues.", howToPlay: "Identify the item or concept shown in each picture." },
  { name: "Quizhead", category: "trivia/quiz", description: "A social trivia app.", howToPlay: "Compete with friends in quiz matches." },
  { name: "Smartypants", category: "trivia/quiz", description: "A trivia game for all ages.", howToPlay: "Answer questions and earn points to win." },
  { name: "Word Blitz", category: "trivia/quiz", description: "A fast-paced word trivia game.", howToPlay: "Form words from a grid of letters within a time limit." },
  { name: "The Logo Game", category: "trivia/quiz", description: "A quiz game about identifying brands and logos.", howToPlay: "Match logos with their respective brands to earn points." },
  { name: "Math Quiz", category: "trivia/quiz", description: "A game focused on solving math problems.", howToPlay: "Answer math-based trivia questions to score points." },
  { name: "General Knowledge Quiz", category: "trivia/quiz", description: "A broad trivia game covering multiple topics.", howToPlay: "Test your general knowledge in a variety of categories." },
  { name: "Guess the Song", category: "trivia/quiz", description: "A music trivia game.", howToPlay: "Identify songs from short clips or lyrics." },
  { name: "Hollywood Quiz", category: "trivia/quiz", description: "A trivia game centered on Hollywood movies.", howToPlay: "Answer questions about movie plots, actors, and awards." },
  { name: "Geo Quiz", category: "trivia/quiz", description: "A geography trivia game.", howToPlay: "Identify locations, landmarks, and maps from the clues." },
  { name: "Brainiac Trivia", category: "trivia/quiz", description: "A game for trivia enthusiasts.", howToPlay: "Answer challenging questions in science, history, and more." },
  { name: "Quiz Factory", category: "trivia/quiz", description: "A customizable quiz game.", howToPlay: "Create and play quizzes on any topic." },
  { name: "Emoji Quiz", category: "trivia/quiz", description: "A game about interpreting emojis.", howToPlay: "Guess phrases or titles based on emoji combinations." },
  { name: "Animal Quiz", category: "trivia/quiz", description: "A trivia game about animals.", howToPlay: "Identify animals from pictures or trivia questions." },
  { name: "Sports Quiz", category: "trivia/quiz", description: "A trivia game for sports enthusiasts.", howToPlay: "Answer questions about teams, players, and sports history." },
  { name: "Science Quiz", category: "trivia/quiz", description: "A trivia game focused on science.", howToPlay: "Test your knowledge in physics, chemistry, biology, and more." },
  { name: "History Quiz", category: "trivia/quiz", description: "A game focused on historical events and figures.", howToPlay: "Answer questions about world history and famous events." },
  { name: "Space Quiz", category: "trivia/quiz", description: "A game about space exploration and astronomy.", howToPlay: "Identify planets, stars, and facts about the universe." },
  { name: "Food Trivia", category: "trivia/quiz", description: "A game about food and culinary topics.", howToPlay: "Answer questions about cuisines, ingredients, and recipes." },
  { name: "Disney Quiz", category: "trivia/quiz", description: "A trivia game focused on Disney movies and characters.", howToPlay: "Answer questions about Disney films, songs, and characters." },
  { name: "Harry Potter Quiz", category: "trivia/quiz", description: "A trivia game for Harry Potter fans.", howToPlay: "Answer questions about the books, movies, and characters." },
  { name: "Star Wars Quiz", category: "trivia/quiz", description: "A game for Star Wars enthusiasts.", howToPlay: "Test your knowledge of Star Wars lore and trivia." },
  { name: "Marvel Quiz", category: "trivia/quiz", description: "A trivia game about Marvel superheroes.", howToPlay: "Answer questions about Marvel movies, comics, and characters." },
  { name: "Netflix Trivia", category: "trivia/quiz", description: "A quiz game about popular Netflix shows.", howToPlay: "Identify characters, plotlines, and episodes from Netflix originals." },
  { name: "Kids Trivia", category: "trivia/quiz", description: "A family-friendly trivia game.", howToPlay: "Answer age-appropriate trivia questions across different categories." },
  { name: "Guess the Flag", category: "trivia/quiz", description: "A geography trivia game about flags.", howToPlay: "Identify the flags of different countries around the world." },
  { name: "Pokemon Quiz", category: "trivia/quiz", description: "A game for Pokemon fans.", howToPlay: "Test your knowledge of Pokemon species, moves, and regions." },
  { name: "Anime Trivia", category: "trivia/quiz", description: "A game for anime enthusiasts.", howToPlay: "Answer questions about anime series, characters, and genres." },
  { name: "Word Association Quiz", category: "trivia/quiz", description: "A quiz game about word connections.", howToPlay: "Find related words or phrases to complete the trivia." },
  { name: "Movie Quotes Quiz", category: "trivia/quiz", description: "A trivia game about famous movie quotes.", howToPlay: "Guess the movie from its iconic lines." },
  { name: "Cartoon Quiz", category: "trivia/quiz", description: "A trivia game about animated shows.", howToPlay: "Answer questions about cartoons and animated films." },
  { name: "Famous People Quiz", category: "trivia/quiz", description: "A game about historical and modern figures.", howToPlay: "Identify famous people from clues or images." },
  { name: "Brand Quiz", category: "trivia/quiz", description: "A game about identifying brands.", howToPlay: "Match brand logos and slogans with their companies." },
  { name: "Fast Food Quiz", category: "trivia/quiz", description: "A trivia game about fast food chains.", howToPlay: "Answer questions about popular fast food items and brands." },
  { name: "Music Trivia", category: "trivia/quiz", description: "A game for music lovers.", howToPlay: "Identify songs, artists, and albums from trivia questions." },
  { name: "TV Show Trivia", category: "trivia/quiz", description: "A quiz game about TV series.", howToPlay: "Answer questions about popular television shows." },
  { name: "Fictional Characters Quiz", category: "trivia/quiz", description: "A game about fictional characters.", howToPlay: "Identify characters from books, movies, or TV shows." },
  { name: "Literature Quiz", category: "trivia/quiz", description: "A trivia game about famous books and authors.", howToPlay: "Answer questions about literary works and writers." },
  { name: "Color Quiz", category: "trivia/quiz", description: "A fun game about colors and their meanings.", howToPlay: "Match colors with their names, shades, or associations." },
  { name: "Video Game Trivia", category: "trivia/quiz", description: "A trivia game for gamers.", howToPlay: "Answer questions about popular games and gaming history." }
);